stages:
  prepare:
    cmd: python pipelines/prepare_data.py
    deps:
    - data/raw
    params:
    - prepare.IM_WIDTH
    - prepare.IM_HEIGHT
  train:
    cmd: python ml/train.py
    deps:
    - data/interim
    params:
    - train.NUM_EPOCHS
    - train.LEARNING_RATE
    - train.TRANSFORMS

params:
- dvclive/params.yaml
artifacts:
  ipreferdogs:
    path: model.pt
    type: model
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
